server:
  port: 8081
  servlet:
    context-path: /api/v2
spring:
  main:
    banner-mode: console
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/ji_project
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: info
